### ISSUE TITLE
ImportError: cannot import name 'Self' from 'typing' (/usr/local/lib/python3.10/typing.py)

### ISSUE THREAD

**Issue by JaredS215** [rockerBOO/sd-webui-daam#5]
When launch after installing, I get the following error:
*** Error loading script: daam.py
    Traceback (most recent call last):
      File "/home/USERNAME/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/USERNAME/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/USERNAME/stable-diffusion-webui/extensions/sd-webui-daam/scripts/daam.py", line 9, in <module>
        from webui_daam.daam import Script
      File "/home/USERNAME/stable-diffusion-webui/extensions/sd-webui-daam/src/webui_daam/daam.py", line 31, in <module>
        from webui_daam.prompt import PromptAnalyzer
      File "/home/USERNAME/stable-diffusion-webui/extensions/sd-webui-daam/src/webui_daam/prompt.py", line 2, in <module>
        from typing import List, Self, Tuple, TypeVar, Union
    ImportError: cannot import name 'Self' from 'typing' (/usr/local/lib/python3.10/typing.py)

**Comment by WooDwayToneTion** [comment]
https://stackoverflow.com/questions/77247446/cannot-import-name-self-from-typing

**Comment by rockerBOO** [comment]
Sorry about the late reply, apparently forks do not have notifications on by default. let me get this fixed up for python 3.10.
